### ISSUE TITLE
Imagens do Manual do Usuário

### ISSUE THREAD

**Issue by luisa-hub** [luisa-hub/e-Agenda-laboratorioprogramacao#4]
![imagem_2021-09-12_185808](https://user-images.githubusercontent.com/72579773/133004016-b4bbf474-a4dc-4974-8b7b-36df8ffb99e4.png)
![imagem_2021-09-12_185849](https://user-images.githubusercontent.com/72579773/133004036-c31e8c47-8ef0-45ce-8347-35062aa588f7.png)
![image](https://user-images.githubusercontent.com/72579773/133004055-272acb64-7872-48e9-9176-6b2c45cd85a7.png)
![image](https://user-images.githubusercontent.com/72579773/133004067-ef76a59b-c083-4d99-9ab1-d9f5f84cbc02.png)
![image](https://user-images.githubusercontent.com/72579773/133004413-4e19d188-88fc-49ef-aa13-0ccc3dc7decc.png)

![image](https://user-images.githubusercontent.com/72579773/133004599-f92bf298-7d3d-4ead-bdc0-5cfeee3c0469.png)
![image](https://user-images.githubusercontent.com/72579773/133004676-88b331a8-3584-4509-a665-43f0e2319614.png)

![image](https://user-images.githubusercontent.com/72579773/133004723-d6613469-dc29-4a22-92fb-6dac010c479d.png)
![image](https://user-images.githubusercontent.com/72579773/133005227-ddef6b5e-ad2f-47a0-8e2c-1c3c8bcbc7d7.png)

![image](https://user-images.githubusercontent.com/72579773/133005290-5cd3c6a5-8b55-4516-9c7f-1cbf1c3d873e.png)
![image](https://user-images.githubusercontent.com/72579773/133005307-c650d9f6-f3af-43bb-919f-637a98096849.png)
![image](https://user-images.githubusercontent.com/72579773/133005374-b1d95d54-9fbb-465b-bbfa-c61b700dc852.png)

**Comment by leandrofomtana** [comment]
(y)
